name: dating_app
description: "Case Study - NodeLabs Software"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #State Man
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  #Dependency Injection
  get_it: ^8.0.3

  # Routing
  go_router: 15.1.3

  # Generator
  equatable: 2.0.7

  # Splash
  flutter_native_splash: ^2.4.1

  # İcons
  flutter_launcher_icons: ^0.14.4


  # Secure_storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # Network
  dio: 5.8.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  http_parser: ^4.1.2


  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.9
  firebase_remote_config: ^5.4.3


  # Logger
  flutter_svg: 2.2.0
  talker_flutter: ^4.3.4
  talker_dio_logger: ^4.9.2
  talker_bloc_logger: ^4.4.1
  logging: ^1.3.0


  #Utlis - UI
  dots_indicator: ^4.0.1
  intl: ^0.20.2
  formz: 0.8.0
  loading_indicator: 3.1.1
  sliver_tools: ^0.2.12
  permission_handler: ^12.0.1
  keyboard_actions: ^4.2.0
  flutter_keyboard_visibility: ^6.0.0
  image_picker: 1.1.2
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  visibility_detector: ^0.4.0+2

  # Business Logic
  path_provider: ^2.1.5
  collection: ^1.19.1
  lottie: ^3.1.2
  jiffy: ^6.3.1


dependency_overrides:
  http: ^1.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Runner
  build_runner: ^2.4.15
  analyzer: ^6.11.0
  rps: ^0.9.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.10.0

  # Analysis
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/resources/
  line_length: 80

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/image/
